version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: hyuga_redis
    restart: always
    volumes:
      - "./deploy/redis:/data"

  ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    container_name: hyuga_ui
    restart: always
    ports:
      - "80:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyuga_api
    ports:
      - 127.0.0.1:5000:5000
      - "53:53/udp"
    depends_on:
      - "redis"
